[package]
name = "test-utils"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
edition = { workspace = true }

[dependencies]
gramax-git = { path = "../git", optional = true }
rstest = "0.21.0"
tempdir = "0.3.7"

[features]
git = ["gramax-git"]
