stages:
  - renovate
  - build-images
  - test
  - build
  - build-dev
  - deploy-dev
  - sync

include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml
  - local: .ci/.templates.yml
  - local: .ci/tests.yml
  - local: .ci/e2e-legacy.yml
  - local: .ci/build.yml
  - local: .ci/build-dev.yml
  - local: .ci/build-apps.yml
  - local: .ci/sync.yml

workflow:
  auto_cancel:
    on_new_commit: interruptible
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release\//
      variables:
        PRODUCTION: "true"
        BRANCH: "master"
        S3_ENV_FOLDER: release
        UPDATER_CHANNEL: "prod"
        BUGSNAG_API_KEY: $BUGSNAG_API_KEY_MASTER
        GITHUB_CLIENT_ID: $GITHUB_CLIENT_ID_MASTER
        GITHUB_CLIENT_SECRET: $GITHUB_CLIENT_SECRET_MASTER
        CONFLUENCE_CLIENT_ID: $CONFLUENCE_CLIENT_ID_MASTER
        CONFLUENCE_CLIENT_SECRET: $CONFLUENCE_CLIENT_SECRET_MASTER
        IS_MERGE_REQUEST: "false"
        BUILD_IMAGES: "true"
        USE_IMAGE_TAG: $PROD_VERSION # TODO: remove 

    - if: $CI_COMMIT_BRANCH == "develop"
      variables:
        PRODUCTION: "true"
        BRANCH: "develop"
        S3_ENV_FOLDER: dev
        S3_BASE_PATH: public/gramax
        UPDATER_CHANNEL: "dev"
        BUGSNAG_API_KEY: $BUGSNAG_API_KEY_DEVELOP
        GITHUB_CLIENT_ID: $GITHUB_CLIENT_ID_DEVELOP
        GITHUB_CLIENT_SECRET: $GITHUB_CLIENT_SECRET_DEVELOP
        CONFLUENCE_CLIENT_ID: $CONFLUENCE_CLIENT_ID_DEVELOP
        CONFLUENCE_CLIENT_SECRET: $CONFLUENCE_CLIENT_SECRET_DEVELOP
        IS_MERGE_REQUEST: "false"
        USE_IMAGE_TAG: "latest-dev"
        BUILD_IMAGES: "true"

    - if: "$CI_COMMIT_TAG"

    - if: '$CI_MERGE_REQUEST_TITLE =~ /^(\[Draft\]|\(Draft\)|Draft:)/'
      when: never

    - if: '$CI_COMMIT_TITLE =~ /!?\[?(skip|no)[ -]ci\]?/i'
      when: never

    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
      variables:
        BRANCH: "master"
        IS_MERGE_REQUEST: "true"
        USE_IMAGE_TAG: latest

    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      variables:
        BRANCH: "develop"
        IS_MERGE_REQUEST: "true"
        USE_IMAGE_TAG: latest-dev

    - when: never
