[workspace]
resolver = "2"
members = [
  "apps/tauri/plugins/plugin-gramax-fs",
  "apps/tauri/plugins/plugin-gramax-git",
  "apps/tauri/src-tauri",

  "apps/browser/wasm",

  "apps/next/rlibs/next-gramax-git",

  "rlibs/git",
  "rlibs/fs",

  "rlibs/test-utils",
  "rlibs/bugsnag",
]

[workspace.package]
version = "0.0.0"
authors = ["ics-it"]
description = "Gramax"
edition = "2021"

[workspace.dependencies]
tauri = { version = "^2.0.0-rc.0", features = [
  "macos-private-api",
  "devtools",
] }
tauri-plugin = { version = "^2.0.0-rc.0", features = ["build"] }
tauri-build = "^2.0.0-rc.0"

tauri-plugin-deep-link = "2.0.0-rc.0"
tauri-plugin-dialog = "^2.0.0-rc.0"
tauri-plugin-log = "^2.0.0-rc.0"
tauri-plugin-updater = { version = "^2.0.0-rc.0", features = ["zip"] }
tauri-plugin-shell = "^2.0.0-rc.0"

serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
log = "^0.4"

[profile.release]
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
