[workspace]
resolver = "2"
members = [
  "apps/tauri/plugins/plugin-gramax-fs",
  "apps/tauri/plugins/plugin-gramax-git",
  "apps/tauri/src-tauri",

  "apps/browser/wasm",

  "apps/next/rlibs/next-gramax-git",

  "rlibs/git",
  "rlibs/fs",
]

[workspace.package]
version = "0.0.0"
authors = ["ics-it"]
description = "Gramax"
edition = "2021"

[workspace.dependencies]
tauri-build = { git = "https://github.com/gram-ax/tauri.git", branch = "locked-version" }


tauri = { git = "https://github.com/gram-ax/tauri.git", branch = "locked-version", features = [
  "macos-private-api",
  "devtools",
] }
tauri-plugin-dialog = { version = "^2.0.0-alpha", git = "https://github.com/gram-ax/tauri-plugins.git", branch = "locked-version" }
tauri-plugin-log = { version = "^2.0.0-alpha", git = "https://github.com/gram-ax/tauri-plugins.git", branch = "locked-version" }
tauri-plugin-updater = { version = "^2.0.0-alpha", git = "https://github.com/gram-ax/tauri-plugins.git", branch = "updater-chunk-timeout" }
tauri-plugin-shell = { version = "^2.0.0-alpha", git = "https://github.com/gram-ax/tauri-plugins.git", branch = "locked-version" }

[profile.release]
codegen-units = 1
lto = true
incremental = false
opt-level = "s"

[patch.crates-io]
tauri = { git = "https://github.com/gram-ax/tauri.git", branch = "locked-version", features = [
  "macos-private-api",
  "devtools",
] }
tauri-build = { git = "https://github.com/gram-ax/tauri.git", branch = "locked-version" }
tauri-plugin-fs = { git = "https://github.com/gram-ax/tauri-plugins.git", branch = "locked-version" }
wry = { git = "https://github.com/pashokitsme/wry.git", branch = "fix-proguard-v0.35.2" }
cc = { git = "https://github.com/pashokitsme/cc-rs.git", branch = "1.0.83-fix-try-expand" }
