.rules:
  if-ci-changed:
    - if: '$CI_COMMIT_BRANCH =~ /^(develop|release\/.*)$/'
      changes:
        - ".ci/**/*"
        - ".gitlab-ci.yml"
        - "vite.config.ts"

  never-if-skip-tests:
    - if: $CI_COMMIT_TITLE =~ /(!?\[?(no|skip).?tests?\]?)/
      when: never

  tests:
    base:
      - !reference [.rules, never-if-skip-tests]
      - if: $CI_COMMIT_TITLE =~ /!?\[?all.?tests?\]?/
      - !reference [.rules, if-ci-changed]
    rust:
      - if: $CI_COMMIT_TITLE =~ /!?\[?all.?tests?\]?/
      - if: '$CI_COMMIT_BRANCH =~ /^(develop|release\/.*)$/ || $CI_PIPELINE_SOURCE == "merge_request_event"'
        changes:
          - "**/*.rs"
          - "**/Cargo.toml"
          - "**/Cargo.lock"
          - ".cargo/**/*"
          - "crates/**/*"

  core:
    - if: $CI_COMMIT_TITLE =~ /!?\[?all.?tests?\]?/
    - !reference [.rules, if-ci-changed]
    - if: '$CI_COMMIT_BRANCH =~ /^(develop|release\/.*)$/'
      changes:
        - app/**/*
        - core/**/*
        - crates/**/*

  build:
    if-prod:
      - if: '$CI_COMMIT_BRANCH == $PROD_BRANCH'
    if-release:
      - if: '$CI_COMMIT_BRANCH =~ /^(release\/.*)$/'
    merge_request:
      - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(develop)$/'
    base:
      - if: '$CI_COMMIT_BRANCH =~ /^(develop|release\/.*)$/'
    service:
      - !reference [.rules, if-ci-changed]
      - if: '$CI_COMMIT_BRANCH =~ /^(develop|release\/.*)$/'
        changes:
          - services/core/**/*
          - services/package.json
          - services/package-lock.json
          - services/target/$IMAGE_NAME/**/*
    rust:
      - if: '$CI_COMMIT_BRANCH =~ /^(develop|release\/.*)$/'
        changes:
          - crates/**/*
    image:
      - if: '$BUILD_IMAGES == "true" && $CI_COMMIT_BRANCH =~ /^(develop|release\/.*)$/'
        changes:
          - .ci/images/*.dockerfile
          - .ci/.templates.yml
          - .ci/build.yml

.template.docker:
  before_script:
    - |
      dockerd --tls=false > /dockerd.log 2>&1 &
      timeout 30s sh -c 'until docker info > /dev/null 2>&1; do sleep 1; echo "Waiting for Docker daemon..."; done'
      docker logout gitlab.ics-it.ru:4567
      echo $GX_TOKEN | docker login gitlab.ics-it.ru:4567 -u "$GX_USER" --password-stdin

.template.github-ssh-key:
  before_script:
    - |
      mkdir -p /root/.ssh
      cat "$GITHUB_ANTI_RATELIMIT_SSH_KEY" > /root/.ssh/github-private-key
      ssh-keyscan github.com > /root/.ssh/known_hosts
      printf "Host github.com\nPreferredAuthentications publickey\nUser git\nIdentityFile /root/.ssh/github-private-key\n" > /root/.ssh/config
      chmod -R 700 /root/.ssh
      chmod 600 /root/.ssh/config
      ssh -T git@github.com || echo "github.com ssh auth"
      git config --global url.ssh://git@github.com/.insteadOf https://github.com/

.template.docker.kubernetes:
  extends: .template.docker.base
  variables:
    BUILDX_DRIVER: "--driver=kubernetes --driver-opt=namespace=${KUBERNETES_NAMESPACE},replicas=1,rootless=true,requests.cpu=1,requests.memory=2Gi,limits.cpu=4,limits.memory=8Gi"

.template.docker.base:
  image: gitlab.ics-it.ru:4567/ics/doc-reader/dind-bun:$USE_IMAGE_TAG
  stage: build
  variables:
    GIT_DEPTH: 600
  tags:
    - kubernetes01-gramax
  # artifacts:
  #   when: always
  #   expire_in: "7 days"
  #   paths:
  #     - trivy-report.txt
  # cache:
  #   - key: trivy
  #     paths:
  #       - .cache/trivy
  before_script:
    - !reference [.template.github-ssh-key, before_script]
    - !reference [.template.docker, before_script]
    - |
      export APP_VERSION=$(./gx version)
      export APP_VERSION_SHORT=$(./gx version --short)

      if [ "$CI_COMMIT_REF_NAME" == "develop" ]; then
        TAG="${APP_VERSION}-dev" # TODO: remove release/YYYY.MM-dev for base images.
        TAG_SHORT="${APP_VERSION_SHORT}-dev"
      elif echo "$CI_COMMIT_REF_NAME" | grep -qE '^release/'; then
        TAG="${APP_VERSION}"
        TAG_SHORT="${APP_VERSION_SHORT}"
      fi

      echo "APP_VERSION: $APP_VERSION"
      echo "APP_VERSION_SHORT: $APP_VERSION_SHORT"
      echo "TAG: $TAG"
      echo "TAG_SHORT: $TAG_SHORT"

      export TAG
      export TAG_SHORT

    - |
      echo ${BUILDX_DRIVER}
      echo "$CI_DEPENDENCY_PROXY_PASSWORD" | docker login $CI_DEPENDENCY_PROXY_SERVER --username $CI_DEPENDENCY_PROXY_USER --password-stdin &&
      echo "$GRAMAX_USER_PASSWORD" | docker login $CI_REGISTRY --username git --password-stdin
