.template.docker.build:
  extends: .template.docker.base
  variables:
    PUSH_ENTERPRISE: "true"
  script:
    - |
      TAGS="$TAG"
      if [ "$CI_COMMIT_REF_NAME" = "develop" ]; then
        TAGS="$TAGS latest-dev"
      elif echo "$CI_COMMIT_REF_NAME" | grep -qE '^release/'; then
        if [ "$CI_COMMIT_REF_NAME" = "$PROD_BRANCH" ]; then
          TAGS="$TAGS latest prod"
        fi
      fi

      echo "CURRENT_VERSION: $CURRENT_VERSION"
      echo "TAGS: $TAGS"

      BUILD_TAGS=""

      for TAG in $TAGS; do
        BUILD_TAGS="$BUILD_TAGS -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:$TAG"

        if [ "$PUSH_ENTERPRISE" = "true" ]; then
          BUILD_TAGS="$BUILD_TAGS -t gitlab.ics-it.ru:4567/gx/enterprise/main/$IMAGE_NAME:$TAG"
        fi
      done

      docker build --rm $BUILD_TAGS \
        -f $DOCKERFILE_PATH --progress=plain --metadata-file build-metadata.json \
        --build-arg BRANCH=$BRANCH \
        --build-arg USE_IMAGE_TAG=$USE_IMAGE_TAG \
        --build-arg BASE_PATH=${BASE_PATH} \
        --build-arg PRODUCTION=$PRODUCTION \
        --build-arg AUTH_SERVICE_URL=$AUTH_SERVICE_URL \
        --build-arg SSO_SERVICE_URL=$SSO_SERVICE_URL \
        --build-arg SSO_SERVICE_ENCRYPTION_KEY=$SSO_SERVICE_ENCRYPTION_KEY \
        --build-arg REVIEW_SERVICE_URL=$REVIEW_SERVICE_URL \
        --build-arg GIT_PROXY_SERVICE_URL=$GIT_PROXY_SERVICE_URL \
        --build-arg DIAGRAM_RENDERER_SERVICE_URL=$DIAGRAM_RENDERER_SERVICE_URL \
        --build-arg BUGSNAG_API_KEY=$BUGSNAG_API_KEY \
        --build-arg COOKIE_SECRET=${COOKIE_SECRET} \
        --build-arg SHARE_ACCESS_TOKEN=${SHARE_ACCESS_TOKEN} \
        --build-arg UPLOAD_SOURCE_MAPS_TO_BUGSNAG=${UPLOAD_SOURCE_MAPS_TO_BUGSNAG} \
        --build-arg CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX=${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX} \
        --build-arg CLOUD_SERVICE_URL=${CLOUD_SERVICE_URL} \
        --build-arg CLOUD_UPLOAD_TOKEN=${CLOUD_UPLOAD_TOKEN} \
        --build-arg APP_VERSION=${APP_VERSION} .

    # - ./.ci/trivy/trivy-image-scan.sh $CI_REGISTRY_IMAGE/$IMAGE_NAME:$TAG

    - |
      for TAG in $TAGS; do
        docker push "$CI_REGISTRY_IMAGE/$IMAGE_NAME:$TAG"
      done

      if [ "$PUSH_ENTERPRISE" = "true" ]; then
        docker logout gitlab.ics-it.ru:4567
        docker login gitlab.ics-it.ru:4567 -u "$GX_USER" -p "$GX_TOKEN"

        for TAG in $TAGS; do
          docker push "gitlab.ics-it.ru:4567/gx/enterprise/main/$IMAGE_NAME:$TAG"
        done
      fi

    - ./.ci/apps/sign.sh --container

.template.docker.build.service:
  extends: .template.docker.build
  variables:
    IMAGE_NAME: $SERVICE_NAME
    DOCKERFILE_PATH: "services/target/$SERVICE_NAME/Dockerfile"
    GIT_DEPTH: 600
    KUBERNETES_MEMORY_REQUEST: "0.5Gi"
    KUBERNETES_CPU_REQUEST: "0.8"
    KUBERNETES_CPU_LIMIT: "2"
  rules: !reference [.rules, build, service]

.template.docker.build.image:
  extends: .template.docker.base
  variables:
    DOCKERFILE_PATH: ".ci/images/$IMAGE_NAME.dockerfile"
    KUBERNETES_MEMORY_REQUEST: "1Gi"
    KUBERNETES_CPU_REQUEST: "1"
    KUBERNETES_CPU_LIMIT: "3"
  rules:
    - !reference [.rules, build, image]
  script:
    - docker build --rm
      -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:$TAG_SHORT
      -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:latest
      -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:latest-dev
      -f $DOCKERFILE_PATH
      --progress=plain
      --metadata-file build-metadata.json
      --build-arg BRANCH=$BRANCH
      --build-arg USE_IMAGE_TAG=$USE_IMAGE_TAG
      --build-arg CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX=${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX} .

    - |
      PUSH_TAGS="$TAG_SHORT"
      if [ "$CI_COMMIT_REF_NAME" = "$PROD_BRANCH" ]; then
        PUSH_TAGS="$PUSH_TAGS latest"
      elif [ "$CI_COMMIT_REF_NAME" = "develop" ]; then
        PUSH_TAGS="$PUSH_TAGS latest-dev"
      fi

      for TAG in $PUSH_TAGS; do
        docker push "$CI_REGISTRY_IMAGE/$IMAGE_NAME:$TAG"
      done

.template.docker.build.opensource:
  extends: .template.docker.base
  rules:
    - !reference [.rules, build, if-prod]
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - .ci/sync/delete-secrets.sh
    - docker build --rm
      -f $DOCKERFILE_PATH
      --build-arg BRANCH=$BRANCH
      --build-arg USE_IMAGE_TAG=$USE_IMAGE_TAG
      --build-arg PRODUCTION=$PRODUCTION
      --build-arg CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX=${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}
      --tag $DOCKERHUB_IMAGE:$TAG
      --tag $DOCKERHUB_IMAGE:latest
      .
    # - ./.ci/trivy/trivy-image-scan.sh $DOCKERHUB_IMAGE:$TAG
    - |
      docker push $DOCKERHUB_IMAGE:$TAG
      if [ "$CI_COMMIT_REF_NAME" = "$PROD_BRANCH" ]; then
        docker push $DOCKERHUB_IMAGE:latest
      fi

bootstrap-dind-bun:
  extends: .template.docker.build.image
  image: docker:28.5.1-dind
  stage: build-images
  variables:
    IMAGE_NAME: "dind-bun"
    NO_TRIVY: "1"
  before_script:
    - |
      apk add --no-cache git curl bash libstdc++ libgcc gcompat
      curl -fsSL https://bun.com/install | bash
      export BUN_INSTALL="$HOME/.bun"
      export PATH="$BUN_INSTALL/bin:$PATH"
      bun --version
    - !reference [.template.docker.build.image, before_script]

build-image-spa:
  extends: .template.docker.build.image
  stage: build-images
  needs:
    - job: bootstrap-dind-bun
      optional: true
  rules: !reference [.rules, build, rust]
  variables:
    IMAGE_NAME: "spa"
    DOCKERFILE_PATH: "./crates/spa/Dockerfile"

build-image-multiplatform:
  extends: .template.docker.build.image
  stage: build-images
  needs:
    - job: build-image-spa
      optional: true
  variables:
    BUILD_PLATFORMS: "linux/amd64,linux/arm64,linux/arm64/v8"
  parallel:
    matrix:
      - IMAGE_NAME: ["base-image", "playwright", "dind-bun"]

build-image:
  extends: .template.docker.build.image
  variables:
    NO_TRIVY: "1"
  needs:
    - job: bootstrap-dind-bun
      optional: true
  stage: build-images
  parallel:
    matrix:
      - IMAGE_NAME: ["linux-tauri"] # TEMP: removed 'build-dev'

build-web:
  extends: .template.docker.build
  rules: !reference [.rules, build, base]
  variables:
    IMAGE_NAME: "web"
    DOCKERFILE_PATH: "./apps/browser/Dockerfile"
    KUBERNETES_MEMORY_REQUEST: "0.3Gi"
    KUBERNETES_CPU_REQUEST: "0.8"
    KUBERNETES_CPU_LIMIT: "1.2"

build-docportal:
  extends: .template.docker.build
  rules: !reference [.rules, build, if-prod]
  variables:
    GIT_DEPTH: 2000
    UPLOAD_SOURCE_MAPS_TO_BUGSNAG: "true"
    IMAGE_NAME: "docportal"
    DOCKERFILE_PATH: "./apps/next/next.Dockerfile"
    KUBERNETES_MEMORY_REQUEST: "1Gi"
    KUBERNETES_CPU_REQUEST: "1"
    KUBERNETES_CPU_LIMIT: "2"

build-blog:
  extends: .template.docker.build
  rules: !reference [.rules, build, if-prod]
  variables:
    GIT_DEPTH: 2000
    PUSH_ENTERPRISE: "false"
    IMAGE_NAME: "blog"
    BASE_PATH: "/resources"
    UPLOAD_SOURCE_MAPS_TO_BUGSNAG: "false"
    DOCKERFILE_PATH: "./apps/next/next.Dockerfile"

build-partners:
  extends: .template.docker.build
  rules: !reference [.rules, build, if-prod]
  variables:
    GIT_DEPTH: 2000
    PUSH_ENTERPRISE: "false"
    IMAGE_NAME: "partners"
    BASE_PATH: "/docs"
    UPLOAD_SOURCE_MAPS_TO_BUGSNAG: "false"
    DOCKERFILE_PATH: "./apps/next/next.Dockerfile"

build-services:
  extends: .template.docker.build.service
  parallel:
    matrix:
      - SERVICE_NAME:
          - auth
          - git-proxy
          - enterprise
          - diagram-renderer
          - cloud

publish-cli:
  tags:
    - kubernetes01-gramax
  stage: build
  image: gitlab.ics-it.ru:4567/ics/doc-reader/base-image:$USE_IMAGE_TAG
  rules: !reference [.rules, build, if-prod]
  when: manual
  before_script:
    - !reference [.template.github-ssh-key, before_script]
    - echo "//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}" > ~/.npmrc
  script:
    - npm whoami
    - ./install-deps.sh --ci
    - bun run --cwd ./apps/gramax-cli build
    - cd ./apps/gramax-cli/dist
    - npm version $(npm show gramax-cli version) --no-git-tag-version
    - npm version patch --no-git-tag-version
    - npm publish

build-assets-cloud:
  extends: .template.docker.build
  rules: !reference [.rules, build, if-prod]
  variables:
    PUSH_ENTERPRISE: "false"
    IMAGE_NAME: "assets-cloud"
    DOCKERFILE_PATH: "./services/target/cloud/Dockerfile.assets"

build-web-opensource:
  extends: .template.docker.build.opensource
  variables:
    DOCKERFILE_PATH: "./apps/browser/Dockerfile"
    DOCKERHUB_IMAGE: "gramax/editor"

build-docportal-opensource:
  extends: .template.docker.build.opensource
  variables:
    GIT_DEPTH: 2000
    DOCKERFILE_PATH: "apps/next/next.Dockerfile"
    DOCKERHUB_IMAGE: "gramax/docportal"

build-git-proxy-opensource:
  extends: .template.docker.build.opensource
  variables:
    DOCKERFILE_PATH: "./services/target/git-proxy/Dockerfile"
    DOCKERHUB_IMAGE: "gramax/git-proxy"

build-diagram-renderer-opensource:
  extends: .template.docker.build.opensource
  variables:
    DOCKERFILE_PATH: "./services/target/diagram-renderer/Dockerfile"
    DOCKERHUB_IMAGE: "gramax/diagram-renderer"
