[package]
name = "gramax"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = { workspace = true }

[lib]
name = "gramax"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "^2.0.0-alpha", features = [] }

[dependencies]
tauri = { workspace = true }
plugin-gramax-fs = { path = "../plugins/plugin-gramax-fs" }
plugin-gramax-git = { path = "../plugins/plugin-gramax-git" }
tauri-plugin-dialog = "^2.0.0-alpha"
tauri-plugin-log = "^2.0.0-alpha"
gramax-git = { path = "../libs/gramax-git" }

color-eyre = "0.6.2"
owo-colors = { version = "3.5.0", optional = true }
dotenvy = "0.15.7"
sys-locale = "0.3.0"
tiny_http = "0.12.0"
serde_json = "1.0.105"
url = "2.4.0"
log = "0.4.20"
semver = { version = "1.0.18", features = ["serde"] }
strum = { version = "0.25.0", features = ["derive"] }

[target.'cfg(any(target_os = "windows", target_os = "macos"))'.dependencies]
tauri-plugin-updater = "^2.0.0-alpha"
tauri-plugin-shell = "^2.0.0-alpha"
tokio = { version = "1.32.0", features = ["time"] }
open = "5.0.0"


[target.'cfg(target_os = "android")'.dependencies]
android-intent = { git = "https://github.com/pashokitsme/android-intent" }

[target.'cfg(target_os = "ios")'.dependencies]
const_format = "0.2.31"
cacao = { version = "0.3.2", default-features = false, features = ["uikit"] }

[features]
self-test = ["dep:owo-colors"]
custom-protocol = ["tauri/custom-protocol"]

[dev-dependencies]
rstest = { version = "0.18.2", default-features = false }
