services:
    gramax:
        build:
            context: ../../
            dockerfile: ./apps/next/next.Dockerfile
            args:
                - DOCKER_BUILDKIT=1
        image: gramax/gramax:latest
        container_name: gramax
        restart: unless-stopped
        ports:
            - ${PORT:-80}:${PORT}
        environment:
            - PORT=${PORT}
            - ADMIN_LOGIN=${ADMIN_LOGIN:-admin}
            - ADMIN_PASSWORD=${ADMIN_PASSWORD:-password}
            - LOGO_IMAGE_URL=${LOGO_IMAGE_URL}
            - LOGO_LINK_URL=${LOGO_LINK_URL}
            - LOGO_LINK_TITLE=${LOGO_LINK_TITLE}
        volumes:
            - ${ROOT_PATH:-./gramax}:/app/data
            # - ./robots.txt:/app/public/robots.txt
            # - ./sitemap.xml:/app/public/sitemap.xml
        networks:
            - gramax-network

    diagram-renderer:
        # build:
        #     context: ../../
        #     args:
        #         - DOCKER_BUILDKIT=1
        #     dockerfile: ./services/target/diagram-renderer/next.Dockerfile
        image: gramax/gramax-diagram-renderer:latest
        container_name: gramax-diagram-renderer
        networks:
            - gramax-network
        restart: unless-stopped

    c4viz:
        image: gramax/gramax-c4-server:latest
        container_name: gramax-c4viz-server
        networks:
            - gramax-network

networks:
    gramax-network:
        name: gramax-network

volumes:
    catalogs:
        name: "catalogs"
