[net]
git-fetch-with-cli = true

[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[target.wasm32-unknown-emscripten]
rustflags = [
  "-Ctarget-feature=+atomics,+bulk-memory",
  "-Clink-args=-pthread -sPTHREAD_POOL_SIZE=8",
  "-Clink-args=--post-js apps/browser/crates/gramax-wasm/js/post.js -o apps/browser/crates/gramax-wasm/dist/gramax-wasm.js",
  "-Clink-args=-sWASM=1 -sWASMFS=1 -sUSE_ZLIB=1 -sEXPORT_ES6=1 -sMALLOC=emmalloc -sEXPORTED_RUNTIME_METHODS=FS,wasmMemory,HEAPU8 -sALLOW_MEMORY_GROWTH=1 -sMAXIMUM_MEMORY=4gb -sINITIAL_MEMORY=1024mb -sSTACK_SIZE=15mb",
  "-Clink-args=-sASYNCIFY=1 -sASYNCIFY_IMPORTS=@.cargo/asyncify-imports",
  "-Clink-args=-sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE=$writeArrayToMemory",
  "-Clink-args=-sEXPORTED_FUNCTIONS=@.cargo/exported-functions",
]
