/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AccessTokenCreds {
  authorName: string
  authorEmail: string
  accessToken: string
  username: string | null
  protocol: string | null
}

export declare function add(repoPath: string, paths: Array<string>, force: boolean, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function add_remote(repoPath: string, name: string, url: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function branch_info(repoPath: string, name?: string | undefined | null, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function branch_list(repoPath: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function cancel(id: number, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function checkout(repoPath: string, creds: AccessTokenCreds, branch: string, create: boolean, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<AsyncOutput>

export declare function clone(creds: AccessTokenCreds, opts: RawCloneOptions, callback: ((err: Error | null, arg: string) => any), spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<AsyncOutput>

export declare function commit(repoPath: string, creds: AccessTokenCreds, opts: CommitOptions, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export interface CommitFilterOptions {
  authors: Array<string> | null
  beforeDate: string | null
  afterDate: string | null
  paths: Array<string> | null
}

export interface CommitInfoOpts {
  depth: number
  simplify: boolean
  filters: CommitFilterOptions | null
  includeChangedFiles: boolean | null
}

export interface CommitOptions {
  message: string
  parentRefs: Array<string> | null
  files: Array<string> | null
}

export interface ConfigValue {
  kind: string
  val: string
}

export declare function copy(scope: string, from: string, to: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function count_changed_files(repoPath: string, searchIn: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function create_or_update_merge_request(repoPath: string, mergeRequest: string, creds: AccessTokenCreds, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function default_branch(repoPath: string, creds: AccessTokenCreds, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function delete_branch(repoPath: string, name: string, remote: boolean, creds?: AccessTokenCreds | undefined | null, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function delete_empty_dirs(scope: string, path: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function diff(opts: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function exists(scope: string, path: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function fetch(repoPath: string, creds: AccessTokenCreds, opts: RemoteOptions, lock: boolean, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<AsyncOutput>

export declare function file_history(repoPath: string, filePath: string, offset: number, limit: number, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function find_refs_by_globs(repoPath: string, pattern: Array<string>, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function format_merge_message(repoPath: string, creds: AccessTokenCreds, opts: MergeMessageFormatOptions, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function gc(repoPath: string, opts: GcOptions, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export interface GcOptions {
  looseObjectsLimit: number | null
  packFilesLimit: number | null
}

export declare function get_all_cancel_tokens(spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function get_all_commit_authors(repoPath: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function get_commit_info(repoPath: string, oid: string, opts: CommitInfoOpts, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function get_config_val(repoPath: string, name: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function get_content(repoPath: string, path: string, oid?: string | undefined | null, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function get_draft_merge_request(repoPath: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function get_parent(repoPath: string, oid: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function get_remote(repoPath: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function getstat(scope: string, path: string, followLink: boolean, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function git_file_exists(repoPath: string, scope: TreeReadScope, path: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function git_file_stat(repoPath: string, scope: TreeReadScope, path: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function git_read_dir(repoPath: string, scope: TreeReadScope, path: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function git_read_dir_stats(repoPath: string, scope: TreeReadScope, path: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function git_read_file(repoPath: string, scope: TreeReadScope, path: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function hardlink(scope: string, from: string, to: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function has_remotes(repoPath: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function healthcheck(repoPath: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function init_new(path: string, creds: AccessTokenCreds, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<AsyncOutput>

export declare function is_bare(repoPath: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function is_init(repoPath: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function lfs_prune(repoPath: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function list_merge_requests(repoPath: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function make_dir(scope: string, path: string, recursive: boolean, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function merge(repoPath: string, creds: AccessTokenCreds, opts: MergeOptions, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export interface MergeMessageFormatOptions {
  theirs: string
  squash: boolean | null
  maxCommits: number | null
  isMergeRequest: boolean | null
}

export interface MergeOptions {
  theirs: string
  deleteAfterMerge: boolean | null
  squash: boolean | null
  isMergeRequest: boolean | null
}

export declare function mv(scope: string, from: string, to: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function new_branch(repoPath: string, name: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function pull_lfs_objects(repoPath: string, creds: AccessTokenCreds, scope: TreeReadScope, paths: Array<string>, checkout: boolean, cancelToken: number, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<AsyncOutput>

export declare function push(repoPath: string, creds: AccessTokenCreds, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<AsyncOutput>

export interface RawCloneOptions {
  branch: string | null
  depth: number | null
  url: string
  to: string
  isBare: boolean
  allowNonEmptyDir: boolean
  skipLfsPull: boolean
  cancelToken: number
}

export declare function read_dir(scope: string, path: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function read_dir_stats(scope: string, path: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function read_file(scope: string, path: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function read_link(scope: string, path: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export interface RemoteOptions {
  cancelToken: number
  force: boolean
}

export declare function remove_dir(scope: string, path: string, recursive: boolean, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function reset(repoPath: string, opts: ResetOptions, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function reset_file_lock(repoPath: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function reset_repo(spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare const enum ResetMode {
  Soft = 'soft',
  Mixed = 'mixed',
  Hard = 'hard'
}

export interface ResetOptions {
  head: string | null
  mode: ResetMode
}

export declare function restore(repoPath: string, staged: boolean, paths: Array<string>, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function rmfile(scope: string, path: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function scan_catalog(scope: string, path: string, docrootRel: string | undefined | null, opts: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function scan_workspace(scope: string, path: string, opts: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function set_config_val(repoPath: string, name: string, val: ConfigValue, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function set_head(repoPath: string, refname: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function stash(repoPath: string, creds: AccessTokenCreds, message?: string | undefined | null, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function stash_apply(repoPath: string, oid: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function stash_delete(repoPath: string, oid: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function status(repoPath: string, index: boolean, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function status_file(repoPath: string, path: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function storage_stats(repoPath: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export interface TreeReadScope {
  objectType: TreeReadScopeObjectType
  reference: string | null
}

export declare const enum TreeReadScopeObjectType {
  Head = 'Head',
  Commit = 'Commit',
  Reference = 'Reference'
}

export declare function unwatch_workspace(id: number, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function watch_workspace(scope: string, root: string, opts: string, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>

export declare function write_file(scope: string, path: string, content: Buffer, compress?: string | undefined | null, spanId?: string | undefined | null, traceId?: string | undefined | null): Promise<unknown>
