export const fsArgOrder: Record<string, string[]> = {
	exists: ["scope", "path"],
	getstat: ["scope", "path", "followLink"],
	read_dir: ["scope", "path"],
	read_dir_stats: ["scope", "path"],
	read_link: ["scope", "path"],
	read_file: ["scope", "path"],
	write_file: ["scope", "path", "content", "compress"],
	make_dir: ["scope", "path", "recursive"],
	remove_dir: ["scope", "path", "recursive"],
	rmfile: ["scope", "path"],
	hardlink: ["scope", "from", "to"],
	copy: ["scope", "from", "to"],
	mv: ["scope", "from", "to"],
	delete_empty_dirs: ["scope", "path"],
	scan_workspace: ["scope", "path", "opts"],
	scan_catalog: ["scope", "path", "docrootRel", "opts"],
	watch_workspace: ["scope", "root", "opts"],
	unwatch_workspace: ["id"],
};
